version: '3'

services:

  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8876:80"
    container_name: nginx-2
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: app-2
    depends_on:
      - db
    #command: bash -c "php artisan migrate && php artisan db:seed && php-fpm"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test_rest_api
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8101:3306"
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
